# Generated by Django 5.2.3 on 2025-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("preco", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="itens/")),
                (
                    "classe_restrita",
                    models.CharField(
                        choices=[
                            ("mago", "Mago"),
                            ("guerreiro", "Guerreiro"),
                            ("arqueiro", "Arqueiro"),
                            ("todas", "Todas"),
                        ],
                        default="todas",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
