# Generated by Django 5.2.3 on 2025-06-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="xp_recompensa",
            field=models.IntegerField(default=10),
        ),
    ]
