# Generated by Django 5.2.2 on 2025-06-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="regiao",
            field=models.CharField(
                choices=[
                    ("floresta_de_go", "floresta_de_go"),
                    ("fortaleza_rustica", "fortaleza_rustica"),
                    ("planicies_julianas", "planicies_julianas"),
                ],
                default="floresta_de_go",
                max_length=20,
            ),
        ),
    ]
