# Generated by Django 5.2.3 on 2025-06-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_regiao"),
    ]

    operations = [
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("avatar", models.ImageField(upload_to="npcs/")),
                ("frase_inicial", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fixo", "fixo"), ("ia", "ia")],
                        default="fixo",
                        max_length=10,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
    ]
