# Generated by Django 5.2.3 on 2025-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_historicodialogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="linguagem",
            field=models.CharField(
                choices=[("golang", "golang"), ("rust", "rust"), ("julia", "julia")],
                default="golang",
                max_length=20,
            ),
        ),
    ]
