# Generated by Django 5.2.3 on 2025-06-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0001_initial"),
        ("progress", "0002_conquista"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarConquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_desbloqueio", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="avatars.avatar"
                    ),
                ),
                (
                    "conquista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="progress.conquista",
                    ),
                ),
            ],
        ),
    ]
