# Generated by Django 5.2.3 on 2025-06-14 00:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0005_usuariomissao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255),
                ),
                (
                    "mensagem",
                    models.TextField(),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conquista", "conquista"),
                            ("xp", "xp"),
                            ("nivel", "nivel"),
                            ("sistema", "sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
