# Generated by Django 5.2.3 on 2025-06-13 17:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import progress.validators


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0006_notificacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conquista",
            name="condicao",
            field=models.CharField(
                max_length=100, validators=[progress.validators.validate_condicao]
            ),
        ),
        migrations.AlterField(
            model_name="missaodiaria",
            name="condicao",
            field=models.CharField(
                max_length=100, validators=[progress.validators.validate_condicao]
            ),
        ),
        migrations.CreateModel(
            name="ProgressoPorLinguagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linguagem",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("golang", "golang"),
                            ("rust", "rust"),
                            ("julia", "julia"),
                        ],
                    ),
                ),
                ("xp_total", models.IntegerField()),
                ("nivel", models.IntegerField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]

