# Generated by Django 5.2.3 on 2025-06-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0009_duelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaDuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.TextField()),
                ("resposta_correta", models.CharField(max_length=255)),
                ("resposta_jogador_1", models.CharField(blank=True, max_length=255)),
                ("resposta_jogador_2", models.CharField(blank=True, max_length=255)),
                ("acertou_1", models.BooleanField(default=False)),
                ("acertou_2", models.BooleanField(default=False)),
                (
                    "duelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="progress.duelo"
                    ),
                ),
            ],
        ),
    ]
