# Generated by Django 5.2.3 on 2025-06-12 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        default="avatars/default.png", upload_to="avatars/"
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("mago", "Mago"),
                            ("guerreiro", "Guerreiro"),
                            ("arqueiro", "Arqueiro"),
                        ],
                        default="guerreiro",
                        max_length=20,
                    ),
                ),
                ("nivel", models.IntegerField(default=1)),
                ("xp_total", models.IntegerField(default=0)),
                ("moedas", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
