# Generated by Django 5.2.3 on 2025-06-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("avatar", "avatar"),
                            ("fundo_perfil", "fundo_perfil"),
                            ("moldura", "moldura"),
                            ("brasao", "brasao"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="skins/")),
                ("preco_moedas", models.IntegerField()),
                (
                    "classe_restrita",
                    models.CharField(
                        choices=[
                            ("mago", "Mago"),
                            ("guerreiro", "Guerreiro"),
                            ("arqueiro", "Arqueiro"),
                            ("todas", "Todas"),
                        ],
                        default="todas",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
